export const coupons = [
    {
        id: 1,
        rating: 3,
        ratings: 195,
        title: 'Cinema',
        short_description: 'The best, bla bla bla',
        name: '360 Orbit Cinema',
        coupon_price: 3,
        coupon_term: 'WAVES',
        old_price: '44',
        new_price: '49',
        price_term: '$',
        discount: 50,
        long_title: 'Lorem Impusm...',
        long_description:
            'Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...',
        status: 'purchased',
        image:
            'https://cdn1.savepice.ru/uploads/2019/6/5/f083cab4bf636dbe751636671a40dbd0-full.png',
    },
    {
        id: 2,
        rating: 2,
        ratings: 442,
        title: 'Cinema',
        short_description: 'The best, bla bla bla',
        name: 'Amazing thing',
        coupon_price: 100,
        coupon_term: 'WAVES',
        old_price: '25',
        new_price: '64',
        price_term: '$',
        discount: 10,
        long_title: 'Lorem Impusm...',
        long_description:
            'Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...',
        status: 'purchased',
        image:
            'https://cdn1.savepice.ru/uploads/2019/6/5/3eaf1f99a32f8045847ac9f02eb81344-full.png',
    },
    {
        id: 3,
        rating: 2,
        ratings: 442,
        title: 'Cinema',
        short_description: 'The best, bla bla bla',
        name: 'Amazing thing',
        coupon_price: 100,
        coupon_term: 'WAVES',
        old_price: '25',
        new_price: '64',
        price_term: '$',
        discount: 10,
        long_title: 'Lorem Impusm...',
        long_description:
            'Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...',
        status: 'purchased',
        image:
            'https://cdn1.savepice.ru/uploads/2019/6/5/3eaf1f99a32f8045847ac9f02eb81344-full.png',
    },
    {
        id: 4,
        rating: 2,
        ratings: 442,
        title: 'Cinema',
        short_description: 'The best, bla bla bla',
        name: 'Amazing thing',
        coupon_price: 100,
        coupon_term: 'WAVES',
        old_price: '25',
        new_price: '64',
        price_term: '$',
        discount: 10,
        long_title: 'Lorem Impusm...',
        long_description:
            'Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...',
        status: 'purchased',
        image:
            'https://cdn1.savepice.ru/uploads/2019/6/5/3eaf1f99a32f8045847ac9f02eb81344-full.png',
    },
    {
        id: 5,
        rating: 2,
        ratings: 442,
        title: 'Cinema',
        short_description: 'The best, bla bla bla',
        name: 'Amazing thing',
        coupon_price: 100,
        coupon_term: 'WAVES',
        old_price: '25',
        new_price: '64',
        price_term: '$',
        discount: 10,
        long_title: 'Lorem Impusm...',
        long_description:
            'Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...',
        status: 'purchased',
        image:
            'https://cdn1.savepice.ru/uploads/2019/6/5/3eaf1f99a32f8045847ac9f02eb81344-full.png',
    },
    {
        id: 6,
        rating: 2,
        ratings: 442,
        title: 'Cinema',
        short_description: 'The best, bla bla bla',
        name: 'Amazing thing',
        coupon_price: 100,
        coupon_term: 'WAVES',
        old_price: '25',
        new_price: '64',
        price_term: '$',
        discount: 10,
        long_title: 'Lorem Impusm...',
        long_description:
            'Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...',
        status: 'purchased',
        image:
            'https://cdn1.savepice.ru/uploads/2019/6/5/3eaf1f99a32f8045847ac9f02eb81344-full.png',
    },
    {
        id: 7,
        rating: 2,
        ratings: 442,
        title: 'Cinema',
        short_description: 'The best, bla bla bla',
        name: 'Amazing thing',
        coupon_price: 100,
        coupon_term: 'WAVES',
        old_price: '25',
        new_price: '64',
        price_term: '$',
        discount: 10,
        long_title: 'Lorem Impusm...',
        long_description:
            'Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...',
        status: 'purchased',
        image:
            'https://cdn1.savepice.ru/uploads/2019/6/5/3eaf1f99a32f8045847ac9f02eb81344-full.png',
    },
    {
        id: 8,
        rating: 2,
        ratings: 442,
        title: 'Cinema',
        short_description: 'The best, bla bla bla',
        name: 'Amazing thing',
        coupon_price: 100,
        coupon_term: 'WAVES',
        old_price: '25',
        new_price: '64',
        price_term: '$',
        discount: 10,
        long_title: 'Lorem Impusm...',
        long_description:
            'Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...',
        status: 'purchased',
        image:
            'https://cdn1.savepice.ru/uploads/2019/6/5/3eaf1f99a32f8045847ac9f02eb81344-full.png',
    },
    {
        id: 9,
        rating: 2,
        ratings: 442,
        title: 'Cinema',
        short_description: 'The best, bla bla bla',
        name: 'Amazing thing',
        coupon_price: 100,
        coupon_term: 'WAVES',
        old_price: '25',
        new_price: '64',
        price_term: '$',
        discount: 10,
        long_title: 'Lorem Impusm...',
        long_description:
            'Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...',
        status: 'purchased',
        image:
            'https://cdn1.savepice.ru/uploads/2019/6/5/3eaf1f99a32f8045847ac9f02eb81344-full.png',
    },
    {
        id: 10,
        rating: 2,
        ratings: 442,
        title: 'Cinema',
        short_description: 'The best, bla bla bla',
        name: 'Amazing thing',
        coupon_price: 100,
        coupon_term: 'WAVES',
        old_price: '25',
        new_price: '64',
        price_term: '$',
        discount: 10,
        long_title: 'Lorem Impusm...',
        long_description:
            'Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...',
        status: 'purchased',
        image:
            'https://cdn1.savepice.ru/uploads/2019/6/5/3eaf1f99a32f8045847ac9f02eb81344-full.png',
    },
    {
        id: 11,
        rating: 2,
        ratings: 442,
        title: 'Cinema',
        short_description: 'The best, bla bla bla',
        name: 'Amazing thing',
        coupon_price: 100,
        coupon_term: 'WAVES',
        old_price: '25',
        new_price: '64',
        price_term: '$',
        discount: 10,
        long_title: 'Lorem Impusm...',
        long_description:
            'Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...',
        status: 'purchased',
        image:
            'https://cdn1.savepice.ru/uploads/2019/6/5/3eaf1f99a32f8045847ac9f02eb81344-full.png',
    },
    {
        id: 12,
        rating: 2,
        ratings: 442,
        title: 'Cinema',
        short_description: 'The best, bla bla bla',
        name: 'Amazing thing',
        coupon_price: 100,
        coupon_term: 'WAVES',
        old_price: '25',
        new_price: '64',
        price_term: '$',
        discount: 10,
        long_title: 'Lorem Impusm...',
        long_description:
            'Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...Lorem Impusm...',
        status: 'purchased',
        image:
            'https://cdn1.savepice.ru/uploads/2019/6/5/3eaf1f99a32f8045847ac9f02eb81344-full.png',
    }
];
